src/Entity/FichierDemande.php
<?php

namespace App\Entity;

use App\Repository\FichierDemandeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: FichierDemandeRepository::class)]
#[Vich\Uploadable]
class FichierDemande
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?string $nom_fichier = null;


    #[ORM\ManyToOne(inversedBy: 'fichierDemandes')]
    private ?User $id_user = null;

    #[ORM\ManyToOne(inversedBy: 'fichierDemandes')]
    private ?Fichier $id_fichier = null;

    #[ORM\ManyToOne(inversedBy: 'fichierDemandes')]
    private ?InfoClient $id_client = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFichier(): ?string
    {
        return $this->nom_fichier ;
    }


    public function setNomFichier(?string $nomFichier): void
    {
        $this->nom_fichier = $nomFichier;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdFichier(): ?Fichier
    {
        return $this->id_fichier;
    }

    public function setIdFichier(?Fichier $id_fichier): self
    {
        $this->id_fichier = $id_fichier;

        return $this;
    }

    public function getIdClient(): ?InfoClient
    {
        return $this->id_client;
    }

    public function setIdClient(?InfoClient $id_client): self
    {
        $this->id_fichier = $id_client;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNomFichier() ?? '';
        }



}

src/Form/FichierDemandeType.php
<?php

namespace App\Form;

use App\Entity\Fichier;
use App\Entity\FichierDemande;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;



class FichierDemandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_fichier', FileType::class, [
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ])


            ->add('id_user' , EntityType::class, [
                'class' => User::class,
            ])
            ->add('id_fichier' , EntityType::class, [
                'class' => Fichier::class,
            ])


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FichierDemande::class,
        ]);
    }
}

src/Controller/FichierDemandeController.php
<?php

namespace App\Controller;
use App\Entity\Fichier;
use App\Entity\InfoClient;
use App\Entity\User;
use App\Entity\FichierDemande;
use App\Form\FichierDemandeType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\FichierDemandeRepository;
use App\Repository\FichierRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use phpDocumentor\Reflection\DocBlock\Serializer;
use Symfony\Component\HttpFoundation\File\File;

#[Route('fichier_demande')]
class FichierDemandeController extends AbstractController
{
    #[Route('/', name: 'app_fichier_demande_index', methods: ['GET'])]
    public function index(FichierDemandeRepository $fichierDemandeRepository): Response
    {
   
    
        $user = $this->getUser();
        $test = $fichierDemandeRepository->findAll();

        // dd($fichierDemandeRepository->findAll());
        return $this->render('fichier_demande/index.html.twig', [
            'fichier_demandes' =>   $fichierDemandeRepository->createQueryBuilder('fd')
            ->leftJoin('fd.id_user', 'u')
            ->leftJoin('fd.id_fichier', 'f')
            ->addSelect('u')
            ->addSelect('f')
            ->getQuery()
            ->getResult(),
            'user'=>$user->getUserIdentifier()
        ]);

    }

    #[Route('/new', name: 'app_fichier_demande_new', methods: ['GET', 'POST'])]
    public function new(EntityManagerInterface $entityManager ,Request $request, UserRepository $userrepo, FichierRepository $fichierrepo, FichierDemandeRepository $fichierDemandeRepository): Response
    {
        $user = $this->getUser();
        $fichierDemande = new FichierDemande();
        $form = $this->createForm(FichierDemandeType::class, $fichierDemande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form->get('nom_fichier')->getData();
              // Il s'agit de l'id du client
            $idUser = $form->get('id_user')->getData()->getId();
            $idUser = $userrepo->find($idUser);
           
               //Il s'agit de l'id du fichier demander pour tout les clients
            $idNomFichier= $form->get('id_fichier')->getData()->getId();
            $idNomFichier = $fichierrepo->find($idNomFichier);

            $nomOriginal = $form->get('nom_fichier')->getData()->getClientOriginalName();

            // le chemin ou le fichier est inserer
            $destinationDirectory = 'D:/XAMPP/htdocs/WEB/DELPH/cms_delph/public/'.'fichier';
            $newFilename = $nomOriginal;
            $uploadedFile->move($destinationDirectory, $newFilename);
            $fichierDemande->setNomFichier($newFilename);
            $fichierDemande->setIdUser($idUser);
            $fichierDemande->setIdFichier($idNomFichier);
            $entityManager->persist($fichierDemande);
            $entityManager->flush();
            $fichierDemandeRepository->save($fichierDemande, true);

            return $this->redirectToRoute('app_fichier_demande_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('fichier_demande/new.html.twig', [
            'fichier_demande' => $fichierDemande,
            'form' => $form,
            'user'=>$user->getUserIdentifier()
        ]);
    }




    #[Route('/{id}/edit', name: 'app_fichier_demande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FichierDemande $fichierDemande, FichierDemandeRepository $fichierDemandeRepository): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(FichierDemandeType::class, $fichierDemande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fichierDemandeRepository->save($fichierDemande, true);

            return $this->redirectToRoute('app_fichier_demande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fichier_demande/edit.html.twig', [
            'fichier_demande' => $fichierDemande,
            'form' => $form,
            'user'=>$user->getUserIdentifier()
        ]);
    }

    #[Route('/{id}', name: 'app_fichier_demande_delete', methods: ['POST'])]
    public function delete(Request $request, FichierDemande $fichierDemande, FichierDemandeRepository $fichierDemandeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fichierDemande->getId(), $request->request->get('_token'))) {
            $fichierDemandeRepository->remove($fichierDemande, true);
        }

        return $this->redirectToRoute('app_fichier_demande_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/{name}', name: 'app_view_pdf', methods: ['GET'])]
    public function view_pdf($name)
    {
        $projectRoot = $this->getParameter('kernel.project_dir');
        $filename = $name;

        $filePath = str_replace('\\', '/', $projectRoot) . '/public/fichier/' . $filename;

        return $this->file($filePath, null, ResponseHeaderBag::DISPOSITION_INLINE);
    }


    #[Route('/{id}', name: 'app_fichier_demande_show', methods: ['GET'])]
    public function show(FichierDemande $fichierDemande): Response
    {
        $pathToFile = 'fichierpdf/' . $fichierDemande->getNomFichier();
        return $this->file($pathToFile);
    }

}

templates/fichier_demande/_delete_form.html.twig
<form method="post" action="{{ path('app_fichier_demande_delete', {'id': fichier_demande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fichier_demande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fichier_demande/_form.html.twig
{{ form_start(form) }}

<div class="p-5" style="width: 800px; background-color: whitesmoke">

    <div>
        <div class="form-group mb-4">
       {# {{ dump(form.id_fichier) }}  #}
            {{ form_label(form.id_user, 'Choisir un client', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_row(form.id_user, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.id_fichier, 'Nom du fichier', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_row(form.id_fichier, {'attr': {'class': 'form-control mt-2'}}) }}


            <br><br>
            <div class="form-group">
                {{ form_label(form.nom_fichier, 'Insérer un fichier', {'label_attr': {'class': 'text-right'}}) }}
                {{ form_row(form.nom_fichier, {'attr': {'class': 'form-control mt-2', 'type': 'type'}}) }}

            </div>

            <button class="btn btn-dark" type="submit">{{ button_label|default('Enregistrer') }}</button>


        </div>
    <br><br>

    {{ form_end(form) }}

templates/fichier_demande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FichierDemande{% endblock %}

{% block body %}
    <h1>Edit FichierDemande</h1>

    {{ include('fichier_demande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fichier_demande_index') }}">back to list</a>

    {{ include('fichier_demande/_delete_form.html.twig') }}
{% endblock %}

templates/fichier_demande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FichierDemande index{% endblock %}

{% block body %}
    <h1>Fichier Demande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom Client</th>
                <th>Mail Client</th>
                <th>Nom_fichier</th>
                <th>Voir pdf</th>
            </tr>
        </thead>
        <tbody>
        {% for fichier_demande in fichier_demandes %}
            <tr>
                <td>{{ fichier_demande.idClient }}</td>
              
                 <td>{{ fichier_demande.idUser.email }}</td>

                <td>{{ fichier_demande.idFichier.nomFichier }}</td>
                <td>
                    <a href="{{ path('app_view_pdf', {'name': fichier_demande.getNomFichier()}) }}" target="_blank">Cliquez ici</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fichier_demande_new') }}">Create new</a>
{% endblock %}

templates/fichier_demande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FichierDemande{% endblock %}

{% block body %}
    <h1>Insérer un nouveau fichier </h1>

    {{ include('fichier_demande/_form.html.twig') }}

    <a href="{{ path('app_fichier_demande_index') }}">Retour à la liste</a>
{% endblock %}

templates/fichier_demande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FichierDemande{% endblock %}

{% block body %}
    <h1>FichierDemande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fichier_demande.id }}</td>
            </tr>
            <tr>
                <th>Nom_fichier</th>
                <td>{{ fichier_demande.nomFichier }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_fichier_demande_index') }}">back to list</a>

    <a href="{{ path('app_fichier_demande_edit', {'id': fichier_demande.id}) }}">edit</a>

    {{ include('fichier_demande/_delete_form.html.twig') }}
{% endblock %}