src/Entity/InfoClient.php
<?php

namespace App\Entity;

use App\Repository\InfoClientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InfoClientRepository::class)]
class InfoClient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $mail_pro = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_societe = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $num_pro = null;

    #[ORM\Column]
    private ?int $num = null;

    #[ORM\Column]
    private ?int $cp = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $siret = null;

    #[ORM\ManyToOne(inversedBy: 'infoClients')]
    private ?User $id_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMailPro(): ?string
    {
        return $this->mail_pro;
    }

    public function setMailPro(string $mail_pro): self
    {
        $this->mail_pro = $mail_pro;

        return $this;
    }

    public function getNomSociete(): ?string
    {
        return $this->nom_societe;
    }

    public function setNomSociete(string $nom_societe): self
    {
        $this->nom_societe = $nom_societe;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getNumPro(): ?string
    {
        return $this->num_pro;
    }

    public function setNumPro(string $num_pro): self
    {
        $this->num_pro = $num_pro;

        return $this;
    }

    public function getNum(): ?int
    {
        return $this->num;
    }

    public function setNum(int $num): self
    {
        $this->num = $num;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSiret(): ?int
    {
        return $this->siret;
    }

    public function setSiret(int $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }
}

src/Form/InfoClientType.php
<?php

namespace App\Form;
use App\Repository\UserRepository;
use App\Entity\Categories;
use App\Entity\InfoClient;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InfoClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('mail_pro')
            ->add('nom_societe')
            ->add('adresse')
            ->add('num_pro')
            ->add('num')
            ->add('cp')
            ->add('ville')
            ->add('siret')
            ->add('id_user', EntityType::class, [
                'class' => User::class,
                'query_builder' => function (UserRepository $userRepository) {
                    return $userRepository->createQueryBuilder('a')
                        ->andWhere('a.roles LIKE :role_comptable OR a.roles LIKE :role_admin')
                        ->setParameter('role_comptable', '%ROLE_COMPTABLE%')
                        ->setParameter('role_admin', '%ROLE_ADMIN%')

                        ->orderBy('a.email');
                }

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => InfoClient::class,
        ]);
    }
}

src/Controller/InfoClientController.php
<?php

namespace App\Controller;

use App\Entity\FichierDemande;
use App\Entity\User;
use App\Entity\InfoClient;
use App\Form\InfoClientType;
use App\Form\UserType;
use App\Repository\InfoClientRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\DocBlock\Serializer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('/info/client')]
class InfoClientController extends AbstractController
{

    #[Route('/', name: 'app_info_client_index', methods: ['GET'])]
    public function index(InfoClientRepository $infoClientRepository): Response
    {
        $user = $this->getUser();
        return $this->render('info_client/index.html.twig', [
            'info_clients' => $infoClientRepository->findAll(),
            'user'=>$user->getUserIdentifier()
        ]);
    }

    #[Route('/new', name: 'app_info_client_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InfoClientRepository $infoClientRepository, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $infoClient = new InfoClient();
        $form = $this->createForm(InfoClientType::class, $infoClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $infoClientRepository->save($infoClient, true);

            return $this->redirectToRoute('app_info_client_index', [], Response::HTTP_SEE_OTHER);
        }

//        $utilisateurs = $userRepository->findBy(['roles' => 'ROLE_ADMIN']);
//
//        $listeNoms = [];
//        foreach ($utilisateurs as $utilisateur) {
//            $listeNoms[$utilisateur->getId()] = $utilisateur->getNom();
//        }

        return $this->renderForm('info_client/new.html.twig', [
            'info_client' => $infoClient,
            'form' => $form,
            'user' => $user->getUserIdentifier(),
//            'listeNoms' => $listeNoms,
        ]);
    }


    #[Route('/show/{id}', name: 'app_info_client_show', methods: ['GET'])]
    public function show(InfoClientRepository $infoClient, $id): Response
    {
//        $clientData = $this->getUser($id);
//        dd($clientData);
        $client = $infoClient->find($id);
//        dd($client);
        $user = $this->getUser($id);
        return $this->render('info_client/show.html.twig', [
            'info_client' => $client,
            'user'=>$user->getUserIdentifier(),

        ]);
    }

    #[Route('/edit/{id}', name: 'app_info_client_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, InfoClient $infoClient, InfoClientRepository $infoClientRepository): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(InfoClientType::class, $infoClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $infoClientRepository->save($infoClient, true);

            return $this->redirectToRoute('app_info_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('info_client/edit.html.twig', [
            'info_client' => $infoClient,
            'form' => $form,
            'user'=>$user->getUserIdentifier()
        ]);
    }

    #[Route('/delete/{id}', name: 'app_info_client_delete', methods: ['POST'])]
    public function delete(Request $request, InfoClient $infoClient, InfoClientRepository $infoClientRepository): Response
    {

        if ($this->isCsrfTokenValid('delete'.$infoClient->getId(), $request->request->get('_token'))) {
            $infoClientRepository->remove($infoClient, true);
        }

        return $this->redirectToRoute('app_info_client_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/mesColab', name:'mesColab', methods:['GET'])]
    public function index1(InfoClientRepository $infoClientRepository, EntityManagerInterface $entityManager): Response
    {

        $user = $this->getUser();

        $clients = $entityManager->getRepository(InfoClient::class)->findBy([
            'id_user' =>$user,
        ]);

        return $this->render('info_client/index.html.twig', [
            'info_clients' => $clients,
            'user'=>$user->getUserIdentifier(),

        ]);

    }

}

templates/info_client/_delete_form.html.twig
<form method="post" action="{{ path('app_info_client_delete', {'id': info_client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ info_client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/info_client/_form.html.twig
{{ form_start(form) }}
<div class="p-5" style=" background-color: whitesmoke;">

    <div class="row">
        <div class="form-group mb-4 col-3">
            {{ form_label(form.id_user, 'Choisir le comptable', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_row(form.id_user, {'attr': {'data-role': 'role_comptable'}}) }} <br>

            {{ form_label(form.nom, 'Nom', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.nom, {'attr': {'class': 'form-control mt-2'}}) }}


        </div>
        <div class="form-group mb-4 col-3">
            {{ form_label(form.prenom, 'Prenom ', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.prenom, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.mail_pro, 'Mail', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.mail_pro, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.nom_societe, 'Nom Societe', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.nom_societe, {'attr': {'class': 'form-control mt-2'}}) }}



        </div>
        <div class="form-group mb-4 col-3">
            {{ form_label(form.adresse, 'Adresse', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.adresse, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.num_pro, 'Numéro professionel', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.num_pro, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.num, 'Numéro de protable', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.num, {'attr': {'class': 'form-control mt-2'}}) }}



        </div>

        <div class="form-group mb-4 col-3">
            {{ form_label(form.cp, 'Code Postal', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.cp, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.ville, 'Ville', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.ville, {'attr': {'class': 'form-control mt-2'}}) }}

            {{ form_label(form.siret, 'Numéro de Siret', {'label_attr': {'class': 'text-right'}}) }}
            {{ form_widget(form.siret, {'attr': {'class': 'form-control mt-2'}}) }}




        </div>

    </div>
    <button class="btn btn-dark">{{ button_label|default('Enregistrer') }}</button >

</div>
</div>
{{ form_end(form) }}

templates/info_client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit InfoClient{% endblock %}

{% block body %}
<div style="display: flex">
    <h1>Modifier un Client</h1>
    <a class="btn btn-dark" style="position: relative; left: 70%" href="{{ path('app_info_client_index') }}">Retour</a>
    <button class="btn btn-dark">{{ button_label|default('Enregistrer') }}</button >

</div>
<br>
<div class="content-form" >



    {{ include('info_client/_form.html.twig', {'button_label': 'Mise à Jour'}) }}
        {{ include('info_client/_delete_form.html.twig') }}


</div>

{% endblock %}

templates/info_client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoClient index{% endblock %}

{% block body %}
<div style="display: flex">
    <h1>Liste des Clients</h1>
    <a href="{{ path('app_info_client_new') }}" class="btn btn-dark" style="position: relative; left: 70%">Nouveau Client</a>
</div>
    <br>
    <table class="table ">
        <thead>
            <tr class="table-dark">
                <th>Comptable Asocié</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Mail_pro</th>
                <th>Nom_societe</th>
                <th>Adresse</th>
                <th>Num_pro</th>
                <th>Num</th>
                <th>Cp</th>
                <th>Ville</th>
                <th>Siret</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for info_client in info_clients %}
            <tr>
                <td>{{ info_client.idUser }}</td>
                <td>{{ info_client.nom }}</td>
                <td>{{ info_client.prenom }}</td>
                <td>{{ info_client.mailPro }}</td>
                <td>{{ info_client.nomSociete }}</td>
                <td>{{ info_client.adresse }}</td>
                <td>{{ info_client.numPro }}</td>
                <td>{{ info_client.num }}</td>
                <td>{{ info_client.cp }}</td>
                <td>{{ info_client.ville }}</td>
                <td>{{ info_client.siret }}</td>
                <td>
                    <a href="{{ path('app_info_client_edit', {'id': info_client.id}) }}"><svg  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152V424c0 48.6 39.4 88 88 88H360c48.6 0 88-39.4 88-88V312c0-13.3-10.7-24-24-24s-24 10.7-24 24V424c0 22.1-17.9 40-40 40H88c-22.1 0-40-17.9-40-40V152c0-22.1 17.9-40 40-40H200c13.3 0 24-10.7 24-24s-10.7-24-24-24H88z"/></svg></a>
                    <a href="{{ path('app_info_client_show', {'id': info_client.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"/></svg></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/info_client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New InfoClient{% endblock %}

{% block body %}
    <h1>Créer un nouveau Client</h1> <a href="{{ path('app_info_client_index') }}">Retour</a>
    <br>
<div class="content-form" >
    {{ include('info_client/_form.html.twig') }}


</div>
{% endblock %}

templates/info_client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoClient{% endblock %}

{% block body %}
    <h1>InfoClient</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Comptable Associé</th>
                <td>{{ info_client.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ info_client.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ info_client.prenom }}</td>
            </tr>
            <tr>
                <th>Mail_pro</th>
                <td>{{ info_client.mailPro }}</td>
            </tr>
            <tr>
                <th>Nom_societe</th>
                <td>{{ info_client.nomSociete }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ info_client.adresse }}</td>
            </tr>
            <tr>
                <th>Num_pro</th>
                <td>{{ info_client.numPro }}</td>
            </tr>
            <tr>
                <th>Num</th>
                <td>{{ info_client.num }}</td>
            </tr>
            <tr>
                <th>Cp</th>
                <td>{{ info_client.cp }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ info_client.ville }}</td>
            </tr>
            <tr>
                <th>Siret</th>
                <td>{{ info_client.siret }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_info_client_index') }}">back to list</a>

    <a href="{{ path('app_info_client_edit', {'id': info_client.id}) }}">edit</a>

    {{ include('info_client/_delete_form.html.twig') }}
{% endblock %}