src/Entity/Fichier.php
<?php

namespace App\Entity;

use App\Repository\FichierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FichierRepository::class)]
class Fichier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_fichier = null;

    #[ORM\OneToMany(mappedBy: 'id_fichier', targetEntity: FichierDemande::class)]
    private Collection $fichierDemandes;

    public function __construct()
    {
        $this->fichierDemandes = new ArrayCollection();
    }

//    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
//    private ?\DateTimeInterface $date_fichier = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFichier(): ?string
    {
        return $this->nom_fichier;
    }

    public function setNomFichier(string $nom_fichier): self
    {
        $this->nom_fichier = $nom_fichier;

        return $this;
    }

//    public function getDateFichier(): ?\DateTimeInterface
//    {
//        return $this->date_fichier;
//    }

//    public function setDateFichier(\DateTimeInterface $date_fichier): self
//    {
//        $this->date_fichier = $date_fichier;
//
//        return $this;
//    }

/**
 * @return Collection<int, FichierDemande>
 */
public function getFichierDemandes(): Collection
{
    return $this->fichierDemandes;
}

public function addFichierDemande(FichierDemande $fichierDemande): self
{
    if (!$this->fichierDemandes->contains($fichierDemande)) {
        $this->fichierDemandes->add($fichierDemande);
        $fichierDemande->setIdFichier($this);
    }

    return $this;
}

public function removeFichierDemande(FichierDemande $fichierDemande): self
{
    if ($this->fichierDemandes->removeElement($fichierDemande)) {
        // set the owning side to null (unless already changed)
        if ($fichierDemande->getIdFichier() === $this) {
            $fichierDemande->setIdFichier(null);
        }
    }

    return $this;
}

    public function __toString(): string
    {
        return $this->getNomFichier() ?? '';
    }
}

src/Form/FichierType.php
<?php

namespace App\Form;

use App\Entity\Fichier;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FichierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_fichier')
//            ->add('date_fichier')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fichier::class,
        ]);
    }
}

src/Controller/FichierController.php
<?php

namespace App\Controller;

use App\Entity\Fichier;
use App\Form\FichierType;
use App\Repository\FichierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\String\u;

#[Route('/fichier')]
class FichierController extends AbstractController
{
    #[Route('', name: 'app_fichier_index', methods: ['GET'])]
    public function index(FichierRepository $fichierRepository): Response
    {
        $user =$this->getUser();
        return $this->render('fichier/index.html.twig', [
            'fichiers' => $fichierRepository->findAll(),
            'user'=>$user->getUserIdentifier()
        ]);
    }


    #[Route('/admin/add', name: 'app_fichier_new1', methods: ['GET'])]
    public function new1( FichierRepository $fichierRepository,EntityManagerInterface $entityManager): Response
    {
        // jappele la fonction pour ajouter un fichier avec le name en get
        $test = $fichierRepository->insert2($entityManager,$_GET['test']);
        return $this->redirectToRoute('app_fichier_index', [], Response::HTTP_SEE_OTHER);
    }



    #[Route('/admin/nouveau_fichier', name: 'app_fichier_new', methods: ['GET'])]
    public function new(Request $request, FichierRepository $fichierRepository): Response
    {
        $user = $this->getUser();
        $fichier = new Fichier();
        $form = $this->createForm(FichierType::class, $fichier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fichierRepository->save($fichier, true);

            return $this->redirectToRoute('app_fichier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fichier/new.html.twig', [
            'fichier' => $fichier,
            'form' => $form,
            'user'=>$user->getUserIdentifier(),
        ]);
    }

    #[Route('/{id}', name: 'app_fichier_show', methods: ['GET'])]
    public function show(Fichier $fichier): Response
    {
        $user=$this->getUser();
        return $this->render('fichier/show.html.twig', [
            'fichier' => $fichier,
            'user'=>$user->getUserIdentifier(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fichier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fichier $fichier, FichierRepository $fichierRepository): Response
    {
        $form = $this->createForm(FichierType::class, $fichier);
        $form->handleRequest($request);
        $user=$this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $fichierRepository->save($fichier, true);

            return $this->redirectToRoute('app_fichier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fichier/edit.html.twig', [
            'fichier' => $fichier,
            'form' => $form,
            'user'=>$user->getUserIdentifier()
        ]);
    }

    #[Route('/{id}', name: 'app_fichier_delete', methods: ['POST'])]
    public function delete(Request $request, Fichier $fichier, FichierRepository $fichierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fichier->getId(), $request->request->get('_token'))) {
            $fichierRepository->remove($fichier, true);
        }

        return $this->redirectToRoute('app_fichier_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/delete/{id}', name: 'app_fichier_delete_file', methods: ['GET'])]
    public function deleteFile( FichierRepository $fichierRepository,Fichier $fichier,Request $request): Response
    {
        if ($this->isCsrfTokenValid('delete' . $fichier->getId(), $request->request->get('_token'))) {
            $fichierRepository->deleteFile($fichier, true);
        }

        return $this->redirectToRoute('app_fichier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/fichier/_delete_form.html.twig
<form method="post" action="{{ path('app_fichier_delete', {'id': fichier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fichier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fichier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/fichier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fichier{% endblock %}

{% block body %}
    <h1>Edit Fichier</h1>

    {{ include('fichier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fichier_index') }}">back to list</a>

    {{ include('fichier/_delete_form.html.twig') }}
{% endblock %}

templates/fichier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fichier index{% endblock %}

{% block body %}
    <h1>tous les fichiers</h1>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_fichier</th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fichier in fichiers %}
            <tr>
                <td>{{ fichier.id }}</td>
                <td>{{ fichier.nomFichier }}</td>

                <td>

{#                    <a href="{{ path('app_fichier_delete_file', {'id': fichier.id}) }}"><svg  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152V424c0 48.6 39.4 88 88 88H360c48.6 0 88-39.4 88-88V312c0-13.3-10.7-24-24-24s-24 10.7-24 24V424c0 22.1-17.9 40-40 40H88c-22.1 0-40-17.9-40-40V152c0-22.1 17.9-40 40-40H200c13.3 0 24-10.7 24-24s-10.7-24-24-24H88z"/></svg></a>#}
{#                    <a href="{{ path('/app_fichier_delete_file', {'id': fichier.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"/></svg></a>#}
                    <a href="{{ path('app_fichier_delete_file', {'id': fichier.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/></svg></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a  href="{{ path('app_fichier_new') }}" class="btn btn-dark">Create new</a>
{% endblock %}

templates/fichier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Fichier{% endblock %}

{% block body %}
    <h1>Create new Fichier</h1>

    {{ include('fichier/_form.html.twig') }}

    <a href="{{ path('app_fichier_index') }}">Retour à la liste</a>
{% endblock %}

templates/fichier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fichier{% endblock %}

{% block body %}
    <h1>Fichier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fichier.id }}</td>
            </tr>
            <tr>
                <th>Nom_fichier</th>
                <td>{{ fichier.nomFichier }}</td>
            </tr>
{#            <tr>#}
{#                <th>Date_fichier</th>#}
{#                <td>{{ fichier.dateFichier ? fichier.dateFichier|date('Y-m-d H:i:s') : '' }}</td>#}
{#            </tr>#}
        </tbody>
    </table>

    <a href="{{ path('app_fichier_index') }}">back to list</a>

    <a href="{{ path('app_fichier_edit', {'id': fichier.id}) }}">edit</a>


{% endblock %}